/***************************************************************/
/* State.h: LC-3b State Class Header File                      */
/***************************************************************/
#pragma once

#include <vector>
#ifdef __linux__
    #include <stdio.h>
    #include "../include/LC3b.h"
#else
    #include "LC3b.h"
#endif

/***************************************************************/
/* Definitaion of  how much LC-3b register file.               */
/***************************************************************/
#define LC3b_REGS 8

/***************************************************************/
/* LC-3b State info.                                           */
/***************************************************************/
typedef struct PipeState_DE_stage_Struct {
  /* Signals generated by DE stage and needed by previous stages in the
    pipeline are declared below. */
  cs_bits de_ucode;
  bits16  de_sr1_data,
          de_sr2_data;
  bits3   de_sr1,
          de_sr2,
          de_cc;
} DE_Stage_Entry;

typedef struct PipeState_AGEX_stage_Struct {
  /* Signals generated by AGEX stage and needed by previous stages in the
    pipeline are declared below. */
  bool  v_agex_ld_reg,
        v_agex_ld_cc;
  bits3 agex_drid;
} AGEX_Stage_Entry;

typedef struct PipeState_MEMORY_stage_Struct {
  /* Signals generated by MEM stage and needed by previous stages in the
    pipeline are declared below. */
  bits16 target_pc,
         trap_pc;
  bits2  mem_pc_mux;
  bool   v_mem_ld_cc,
         v_mem_ld_reg;
  bits3  mem_drid;
} MEMORY_stage_Entry;

typedef struct PipeState_STORE_stage_Struct {
  /* Signals generated by SR stage and needed by previous stages in the
    pipeline are declared below. */
  bool   sr_n,
         sr_z,
         sr_p,
         v_sr_ld_cc,
         v_sr_ld_reg;
  bits16 sr_reg_data;
  bits3  sr_drid;
} STORE_stage_Entry;

enum TrapCause { TRAP_NONE, TRAP_INTERRUPT, TRAP_EXCEPTION };

enum TRAP_State {
  TRAP_IDLE,
  TRAP_SWAP_STACK,   // Save USP, load SSP into R6 (if in user mode)
  TRAP_PUSH_PSR,     // Push original PSR onto supervisor stack
  TRAP_PUSH_PC,      // Push PC onto supervisor stack, update PSR
  TRAP_VECTOR_READ   // Read handler address from vector table, set PC
};

struct TrapContext {
  TrapCause cause          = TRAP_NONE;
  bool      update_priority = false; // true for interrupts, false for exceptions
  bits16    pc_to_push;              // interrupt: current PC; exception: faulting PC (NPC-2)
  bits16    vector_addr;             // pre-computed vector table address
  bits3     new_priority;            // only used when update_priority == true
};

typedef struct PipeState_Hazards_Struct {
  /* Internal stall signals */
  bool dep_stall,
       v_de_br_stall,
       v_agex_br_stall,
       v_mem_br_stall,
       mem_stall,
       interrupt_stall,
       icache_r;
} Stall_Entry;

class Simulator;
class State
{
  public:
  State(Simulator & instance) : _simulator(instance) {}
  ~State(){}

  Simulator & simulator() { return _simulator; }

  void init_state();
  void SetProgramCounter(const bits16 & val) { PC = val; }
  bits16 GetProgramCounter() const {return PC; }
  bool GetNBit() const { return PSR[2]; };
  bool GetZBit() const { return PSR[1]; };
  bool GetPBit() const { return PSR[0]; };
  bits3 GetNZP();
  void SetDataForRegister(const bits3 & reg, const bits16 & data);
  bits16 GetRegisterData(const bits3 & reg) const;
  void rdump(FILE * dumpsim_file);

  Stall_Entry & Stall() { return stall_sigs; }
  AGEX_Stage_Entry & AgexSignals() {return agex_sigs; }
  DE_Stage_Entry & DecodeSignals() {return decode_sigs; }
  MEMORY_stage_Entry & MemSignals() {return memory_sigs; }
  STORE_stage_Entry & SrSignals() {return store_sigs; }

  // PSR (Processor Status Register) methods
  void SetPSR(const bits16 & val) { PSR = val; }
  bits16 GetPSR() const { return PSR; }
  bool IsPrivilegeMode() const { return PSR[15]; }  // 0=supervisor, 1=user
  void SetPrivilegeMode(bool user_mode) { PSR[15] = user_mode; }
  void TriggerPrivilegeException() { privilege_exception = true; }
  bool HasPrivilegeException() const { return privilege_exception; }
  void TriggerExceptionPending(bool pending) { exception_pending = pending; }
  bool IsExceptionPending() const { return exception_pending; }
  void ClearExceptionPending() { exception_pending = false; }
  void ClearPrivilegeException() { privilege_exception = false; }
  void SetPriorityLevel(bits3 level) { PSR.range<10,8>() = level.range<2,0>(); }
  bits3 GetPriorityLevel() const { return PSR.range<10,8>(); }
  void SetTrapState(TRAP_State s) { trap_state = s; }
  TRAP_State GetTrapState() const { return trap_state; }
  TrapContext & GetTrapContext() { return trap_ctx; }
  const TrapContext & GetTrapContext() const { return trap_ctx; }

  private:
  Simulator & _simulator;
  /**************************************************************/
  /* The LC3-b registers                                        */
  /**************************************************************/
  std::vector<bits16> REGS;

  /***************************************************************/
  /* architectural state                                         */
  /***************************************************************/
  bool privilege_exception = false;
  bool exception_pending   = false;
  bits16 PC;
  bits16 PSR;
  TRAP_State  trap_state = TRAP_IDLE;
  TrapContext trap_ctx;

  DE_Stage_Entry decode_sigs;
  AGEX_Stage_Entry agex_sigs;
  MEMORY_stage_Entry memory_sigs;
  STORE_stage_Entry store_sigs;
  Stall_Entry stall_sigs;
};